plugins {
	id 'java'
}

repositories {
	mavenCentral()
}

dependencies {
	testImplementation(platform('org.junit:junit-bom:5.10.2'))
	testImplementation('org.junit.jupiter:junit-jupiter')
	testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

sourceSets {
	main {
		java {
			srcDirs = ['code']
			exclude '**/*Test.java'
		}
	}
	test {
		java {
			srcDirs = ['code']
		}
	}
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(24)
	}
}

test {
	useJUnitPlatform()
	testLogging {
		events 'passed', 'skipped', 'failed'
		exceptionFormat 'full'
		showStandardStreams = true
	}
}
